version: '2'
services:
    sbox-app:
        image: sbox
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sbox-mysql:3306/sbox?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sbox-mysql:
        extends:
            file: mysql.yml
            service: sbox-mysql
